---
title: "Progress Report"
author: "NorahW3"
date: "2022-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(Lahman)
library(rvest)
library(dplyr)
library(stringr)
library(Lahman)
library(purrr)

```




```{r}
library(rvest)
library(dplyr)
library(stringr)
library(Lahman)
library(purrr)
library(readr)

# Manual ballots/needed per year (replace with actual values if known)
ballots_needed_per_year <- list(
  `2025` = list(ballots=394, needed=296),
  `2024` = list(ballots=385, needed=289),
  `2023` = list(ballots=398, needed=292),
  `2022` = list(ballots=394, needed=296),
  `2021` = list(ballots=401, needed=301),
  `2020` = list(ballots=397, needed=298),
  `2019` = list(ballots=425, needed=319),
  `2018` = list(ballots=398, needed=299),
  `2017` = list(ballots=442, needed=332),
  `2016` = list(ballots=440, needed=330),
  `2015` = list(ballots=549, needed=412),
  `2014` = list(ballots=571, needed=429),
  `2013` = list(ballots=569, needed=299),
  `2012` = list(ballots=573, needed=427),
  `2011` = list(ballots=581, needed=436),
  `2010` = list(ballots=539, needed=405)

)

# Scrape a single year
get_hof_lahman_format <- function(year) {
  
  url <- paste0("https://www.baseball-reference.com/awards/hof_", year, ".shtml")
  html_hof <- tryCatch(read_html(url), error = function(e) return(NULL))
  if(is.null(html_hof)) return(NULL)
  
  tbl_node <- html_hof %>% html_element("#hof_BBWAA")
  if(is.na(tbl_node)) return(NULL)
  
  tbl <- html_table(tbl_node, fill=TRUE)
  colnames(tbl) <- make.unique(as.character(tbl[1,]))
  tbl <- tbl[-1, ]
  colnames(tbl) <- make.unique(colnames(tbl))
  
  # Detect key columns
  name_col  <- intersect(c("Player","Name","Candidate"), colnames(tbl))[1]
  votes_col <- intersect(c("Votes","Vote","Votes Received"), colnames(tbl))[1]
  yrs_col   <- intersect(c("Yrs on Ballot","Yr","Years"), colnames(tbl))
  
  tbl <- tbl %>% rename(name = all_of(name_col), votes = all_of(votes_col))
  if(length(yrs_col)>0) tbl <- tbl %>% rename(num = all_of(yrs_col[1])) else tbl$num <- NA
  tbl$votes <- suppressWarnings(as.integer(tbl$votes))
  tbl$name <- str_remove(tbl$name, "\\*")
  
  # Get ballots/needed for this year
  info <- ballots_needed_per_year[[as.character(year)]]
  if(is.null(info)) info <- list(ballots=NA, needed=NA)
  
  # Compute inducted
  tbl$inducted <- if_else(tbl$votes >= info$needed, "Y", "N")
  
  # Add Lahman fields
  tbl <- tbl %>%
    mutate(
      ballots = info$ballots,
      needed  = info$needed,
      needed_note = NA_character_,
      votedBy = "BBWAA",
      category = "Player",
      yearID = year
    )
  
  # Match to Lahman People
  people_names <- People %>% mutate(fullName=paste(nameFirst,nameLast)) %>% select(playerID, fullName)
  tbl <- tbl %>% left_join(people_names, by=c("name"="fullName")) %>% mutate(playerID = if_else(is.na(playerID),"unk",playerID))
  
  tbl %>% select(playerID, yearID, votedBy, ballots, needed, votes, inducted, category, needed_note, num)
}

# Scrape multiple years
years <- 2025:2023  # Extend as needed
hof_lahman <- map_df(years, get_hof_lahman_format)

# Remove last column and sort
hof_lahman <- hof_lahman %>% select(-last_col()) %>% arrange(playerID)

# Save CSV
write_csv(hof_lahman, "HallOfFame_2025.csv")
hof_lahman

```







